### ISSUE TITLE
running error "anchor test --skip-local-validator "

### ISSUE THREAD

**Issue by YYBer** [thedatadudech/lottery#1]
anchor test --skip-local-validator                     
    Finished release [optimized] target(s) in 0.45s
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.70s
     Running unittests src/lib.rs (/Users/user/Desktop/lottery/target/debug/deps/lottery-5fa7410f17a1ed27)
Deploying cluster: http://127.0.0.1:8899
Upgrade authority: /Users/user/.config/solana/id.json
Deploying program "lottery"...
Program path: /Users/user/Desktop/lottery/target/deploy/lottery.so...
Error: RPC request error: cluster version query failed: error sending request for url (http://127.0.0.1:8899/): error trying to connect: tcp connect error: Connection refused (os error 61)
There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.

**Comment by thedatadudech** [comment]
@YYBer  do you need assistance here, or why did you raise this Issue

**Comment by YYBer** [comment]
do you have this error when you run "anchor test --skip-local-validator"? This command line is from readme.

**Comment by thedatadudech** [comment]
this error occurs I think, if you have no local-validator running, I should write it more clearly to avoid misunderstanding
